name = "GaloisFields"
uuid = "8d0d7f98-d412-5cd4-8397-071c807280aa"
authors = ["Timo Kluck <tkluck@infty.nl>"]
version = "0.4.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.0"
